create public synonym user_action for ANDREW_KANTAROVICH.user_package;
create public synonym admin_action for ANDREW_KANTAROVICH.admin_package;

CREATE PUBLIC SYNONYM Customers FOR ANDREW_KANTAROVICH.Customers_Table;
CREATE PUBLIC SYNONYM Admins FOR ANDREW_KANTAROVICH.Admins_Table;
CREATE PUBLIC SYNONYM Category FOR ANDREW_KANTAROVICH.Category_Table;
CREATE PUBLIC SYNONYM MenuItems FOR ANDREW_KANTAROVICH.MenuItems_Table;
CREATE PUBLIC SYNONYM Orders FOR ANDREW_KANTAROVICH.Orders_Table;
CREATE PUBLIC SYNONYM OrderItems FOR ANDREW_KANTAROVICH.OrderItems_Table;
CREATE PUBLIC SYNONYM Positions FOR ANDREW_KANTAROVICH.Positions_Table;
CREATE PUBLIC SYNONYM Employees FOR ANDREW_KANTAROVICH.Employees_Table;
CREATE PUBLIC SYNONYM Tables FOR ANDREW_KANTAROVICH.Tables_Table;
CREATE PUBLIC SYNONYM Reservations FOR ANDREW_KANTAROVICH.Reservations_Table;

DROP PUBLIC SYNONYM Customers;
DROP PUBLIC SYNONYM Admins;
DROP PUBLIC SYNONYM Category;
DROP PUBLIC SYNONYM MenuItems;
DROP PUBLIC SYNONYM Orders;
DROP PUBLIC SYNONYM OrderItems;
DROP PUBLIC SYNONYM Positions;
DROP PUBLIC SYNONYM Employees;
DROP PUBLIC SYNONYM Tables;
DROP PUBLIC SYNONYM Reservations;

drop public synonym user_action;
drop public synonym admin_action;